### ISSUE TITLE
Long search results displace price

### ISSUE THREAD

**Issue by michaelsanford** [michaelsanford/fitness-go#10]
inline-block price element can be displaced by long info text.

**Comment by tashavitale** [comment]
![issue](https://cloud.githubusercontent.com/assets/26534033/24232565/18064ac4-0f62-11e7-97f8-6c40d5610eff.PNG)

So, this issue happened again...

**Comment by michaelsanford** [comment]
@tashavitale You can reopen issues like this. I'll take a look!
