### ISSUE TITLE
Link to Social Media

### ISSUE THREAD

**Issue by tashavitale** [michaelsanford/fitness-go#13]
Can we implement a "fake link" to follow us on Facebook and Twitter?

**Comment by michaelsanford** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9935306-233980790_58-s1-v1.png?transparent=1&palette=1&width=246)

Yes.

**Comment by tashavitale** [comment]
![instagram](https://cloud.githubusercontent.com/assets/26534033/24384741/1a6d54e4-1334-11e7-8942-05332b336918.png)

**Comment by tashavitale** [comment]
![facebook](https://cloud.githubusercontent.com/assets/26534033/24384774/48ba7eda-1334-11e7-8e2d-8abc5b72ea73.png)

**Comment by tashavitale** [comment]
![twitter](https://cloud.githubusercontent.com/assets/26534033/24384794/669e6808-1334-11e7-9684-6de3559bffdc.png)

**Comment by tashavitale** [comment]
![facebook](https://cloud.githubusercontent.com/assets/26534033/24384849/bf2a831c-1334-11e7-8045-438786a6e69d.png)
