### ISSUE TITLE
Style Become a Member page

### ISSUE THREAD

**Issue by michaelsanford** [michaelsanford/fitness-go#3]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212371-233980790_56-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by tashavitale** [comment]
In the textboxes, can you put something other than my name (LOL)?
I was thinking:
First Name: John
Last Name: Smith
Phone Number: 555 555 5555
Email Address: example@example.com

Or... better yet... not have the titles... and just put the information directly in the textboxes.

**Comment by michaelsanford** [comment]
Ah yes, I meant to take that out.

**Comment by michaelsanford** [comment]
I  left the field labels because it's a best practice for accessibility.

We can discuss removing them again if you want to for rc1.
