### ISSUE TITLE
Add Ads

### ISSUE THREAD

**Issue by michaelsanford** [michaelsanford/fitness-go#9]
@tashavitale Despite having discussed putting them on the right sidebar, it would be better to put them inline, into the result list, since they are all of _different sizes_.

So you would get the list of results, and before the first result you'd have one of the ads. It will flow much better and that's what Google and other social media do, for example..

What do you think?

**Comment by tashavitale** [comment]
I agree. I like the idea actually.

**Comment by michaelsanford** [comment]
Ok @tashavitale I'll do that for rc1 and we can see how we like it. 👍

**Comment by tashavitale** [comment]
We only see one ad in the search results. Can we have a few more show up?
